### ISSUE TITLE
[Elao - App - Docker] Todo

### ISSUE THREAD

**Issue by nervo** [manala/manala-recipes#184]
- [ ] Mutagen compose
  - [ ] Some commands (like `exec`) needs project name be passed by environment variable `COMPOSE_PROJECT_NAME` instead of parameter `--project-name`. Fill upstream issue.
- [ ] Jenkins
    - [ ]  Update `Jenkinsfile` path in jenkins config (two step move, this is the second one :) )
  - [ ] Change `XDG_CACHE_HOME` default value from `/srv/.cache/` to `/srv/cache` in jenkins cloud config
- [ ] Ports range
  - [ ] Explain in README.md
- [ ] Allow cd'ing in the same directory app on the docker container that we were on the host when we `make sh`
- [ ] Check mailhog docker image availability on arm64 (other alternatives if needed: mailcatcher, maildrop, maillocal, smtp4dev)
- [ ] Elasticsearch as an official docker image instead of debian packages, just like on Jenkins
- [ ] Other services as a official docker images instead of debian packages ? redis ? ... ?
- [ ] Generic `make docker [PARAMS]` command
  - [ ] Add a little bafouille on the `make docker logs -f` -> `make docker logs -- -f` trick
- [ ] Release / Deploy
  - [ ] ansible stdout/stderr output
  - [ ] double `https://` in url commit description on github action
- [ ] Replace `zsh`/`oh-my-zsh` to native `bash` and starship
- [ ] Some ports (10080, ...) are blocked by firefox. A little bafouille on it
- [ ] Remove manala.roles related requirements once they are set upstream
- [ ] Symfony cli as debian package
- [ ] Split ansible repository into system/release/deploy, so that provisionning could be made during the docker build with *only* the related system stuff, avoiding build cache invalidation fo every little change in release/deploy
